name: All Things Jeremy
favicon: null
layout_spectrum: 0.23832
typography_spectrum: 0.90942
title: The wonderful world of being a catalyst
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#6d3b2c'
    - '#bd7842'
    - '#c30000'
    - '#536c26'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
